#!/bin/bash

###################################
# Software & Firmware Installation#
###################################

apt-get update
apt-get upgrade
apt-get install rpi-update ampache

rpi-update


###################################
# Reboot is required							#
###################################
shutdown -r now
