#!/bin/bash

###################################
# Software & Firmware Installation#
###################################

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install -y rpi-update ampache 

# for gmrender-resurrect
sudo wget -O - http://www.chiark.greenend.org.uk/~christi/debian/christi@coraline.org.gpg.key | sudo apt-key add -
sudo echo "deb http://www.chiark.greenend.org.uk/~christi/debian/ wheezy main" > /etc/apt/sources.list.d/upnprender.list

sudo apt-get install -y libupnp-dev libgstreamer1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-alsa autoconf

mkdir ~/git
cd ~/git
git clone https://github.com/hzeller/gmrender-resurrect.git
cd gmrender-resurrect
./autogen.sh
./configure
sudo make install

sudo cp scripts/init.d/gmediarenderer /etc/init.d


sudo rpi-update


###################################
# Reboot is required							#
###################################
sudo shutdown -r now
